### ISSUE TITLE
Не открывается лог

### ISSUE THREAD

**Issue by nickmoop** [ivanus0/sl_tools#1]
Здравствуйте. 
Пытаюсь открыть лог сигналки (starline s96, прошивка 2.24.3), пишет что возможно это не лог. Можете подсказать что не так?
Логи:

[sl_log.log](https://github.com/ivanus0/sl_tools/files/13447604/sl_log.log)
[S96 S912 132165-2023_11_22-23_06_32.zip](https://github.com/ivanus0/sl_tools/files/13447605/S96.S912.132165-2023_11_22-23_06_32.zip)

Спасибо за скрипт!

**Comment by ivanus0** [comment]
Этот файл .log действительно имеет формат отличный от лог файлов starline и не содержит событий работы сигналки. Из этого файла можно достать метаданные о текущей конфигурации, типа:
```
<metaField name="Дата установки" value=""/>
<metaField name="№ заказ-наряда" value=""/>
<metaField name="Ф.И.О. мастера" value=""/>
<metaField name="Ф.И.О. клиента" value=""/>
<metaField name="Автомобиль" value=""/>
<metaField name="Номер автомобиля" value=""/>
<metaField name="VIN автомобиля" value=""/>
<comment value=""/>
<settingsChangeDate value="22.11.2023 23:02:47"/>
<settingsChangeLogin value=""/>
```
Те же строки есть и в файле конфигурации.
Я не знаю как получаются подобные файлы. Несколько раз встречал похожие. Может быть это какой-то сбой в работе сигналки или неисправность флеш памяти...

Сколько времени прошло между снятием предыдущего лога и этого?

**Comment by nickmoop** [comment]
запись нового лога помогла. файл можно прочитать. спасибо!
